package io.metacloud.console.logger.enums;

public enum MSGType {

 MESSAGETYPE_INFO, MESSAGETYPE_WARN, MESSAGETYPE_ERROR, MESSAGETYPE_NETWORK, MESSAGETYPE_SETUP, MESSAGETYPE_EMPTY, MESSAGETYPE_COMMAND

}
