package io.metacloud.console.logger.enums;

public enum MSGType {

 MESSAGETYPE_INFO, MESSAGETYPE_WARN, MESSAGETYPE_ERROR, MESSAGETYPE_NETWORK, MESSAGETYPE_NETWORK_FAIL, MESSAGETYPE_SETUP, MESSAGETYPE_EMPTY, MESSAGETYPE_COMMAND, MESSAGETYPE_SUCCESS

}
